### ISSUE TITLE
Incorrect hanling of prerelease in constraints

### ISSUE THREAD

**Issue by nbkolchin** [hashicorp/go-version#101]
```go
  v, _ := version.NewVersion("1.1.8-alpha1")
  if fast_check, err := version.NewConstraint(">= 1.1.7"); err == nil {
    if fast_check.Check(v) {
      fmt.Printf("OK: %v >= 1.1.7\n", v)
    } else {
      fmt.Printf("BUG: %v < 1.1.7\n", v)
    }
```

Constraint check incorrectly returns `false`, which is obviously a bug.

**Comment by Noksa** [comment]
Any updates?

**Comment by tgross** [comment]
I just ran into this today while working on https://github.com/hashicorp/nomad/pull/14821 and I'd forgotten you need to use the [`Core()`](https://pkg.go.dev/github.com/hashicorp/go-version#Version.Core) method to get the expected results here. See https://go.dev/play/p/Dq_2dmVV7Dg

**Comment by nbkolchin** [comment]
It is kinda unclear why we should use `Core()` here.

**Comment by Noksa** [comment]
I would say It is totally ucnlear
