### ISSUE TITLE
Careful with PRs

### ISSUE THREAD

**Issue by StabbyCutyou** [hashicorp/go-version#23]
This is just a minor issue - I don't need it corrected or anything, just something I wanted to bring to your attention so that no future contributors get bit by it.

I'm about to pull this into a new project and was reviewing the change history just to get up to date with the project (it's a small history, so easy to pick through the changes) and I noticed something:

This commit from a PR a few months ago: https://github.com/hashicorp/go-version/commit/0929ab3c34f014b6e0aeb5264c3f0eeec1dd75ec

It has what appears to be a rogue merge-commit that de-attributes my contributions from the contributor graph from a PR a few weeks prior to that one: https://github.com/hashicorp/go-version/commit/b6629851bed46f07f214ed4275b4c7b0cdcdb860

It looks like the contributor had merged changes into his local fork, did a merge commit, then pushed that commit up with his PR, essentially overwriting my own (instead of rebasing the changes cleanly on top of his local copy first). Since the commit wouldn't have shown up in the diff (since all the changes were applied already), I'm guessing it was simply easy to overlook. My commits are still in the history, but it no longer counts the contributions towards me personally. Which, to be honest, is not that big of a deal. I don't think anyone had any ill-intent.

I'm only opening the issue so that someone on your end can acknowledge it and close it out, and then be on the lookout for it so that no future contributors have it happen to them as well.

Love the stuff you all do, thanks again for all the hard work.

**Comment by mitchellh** [comment]
Thanks for pointing this out. Yes, I legitimately had no idea since I just looked at the final diff (not a per-commit diff) and didn't see anything out of the ordinary there.

As you said, I'm sure no one had any ill intent (neither me nor the contributor). I'm sure it was a slip of `git`, which is very easy to do. Sorry for losing your attribution, I'm glad you still have others in the history though.

I'll watch out in the future!

**Comment by StabbyCutyou** [comment]
Thanks for the quick reply, Appreciate the response.
