### ISSUE TITLE
Segments vs Segments64 - there's a significant difference!

### ISSUE THREAD

**Issue by viktorbenei** [hashicorp/go-version#24]
Related commit: https://github.com/hashicorp/go-version/commit/efb921af39aae3824c2805ee533ea4c00a7fd9a2#diff-ccde124315e74e68fae484840d08dff5L272

Previously `Segments()` simply returned `v.segments`, while now it creates a new slice and fills up the new slice with the values, but `Segments64` does not!

The difference is that if you simply return `v.segments` that will be returned __by reference__ and not __by value__.

So, e.g.:

```
ver.Segments64()[segmentIdx] = ver.Segments64()[segmentIdx] + 1
```

`ver` will actually change, but with `Segments()`

```
ver.Segments()[segmentIdx] = ver.Segments()[segmentIdx] + 1
```

`ver` will _not_ change!

Before the linked commit `ver.Segments()` did return the reference, so it did bump the version, but since the linked commit it does not.

A related question: if the intention here is that `ver.Segments()` should return a "copy" and not a reference of `segments`, what would be the best way to bump the version? Maybe a new `version.NewVersionFromSegments` method?

**Comment by viktorbenei** [comment]
A version bump related PR: https://github.com/hashicorp/go-version/pull/9/files

**Comment by mitchellh** [comment]
Yes, I think we should return a copy to match Segments, updating now.
