### ISSUE TITLE
2-segment versions

### ISSUE THREAD

**Issue by r0mant** [hashicorp/go-version#26]
Hey guys,

We've noticed that versions like `1.0` do not produce an error during parsing and are interpreted like `1.0.0`, even though it does not appear to be a correct SemVer.

From http://semver.org/:

```
A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers...
```

The README also says `Versions used with go-version must follow SemVer`, yet the examples show plenty of two-segment versions.

So given all that:

* Is this intended behavior?
* Are there any plans/thoughts to make the parser stricter and reject incorrect SemVer versions? or
* Would you accept a PR that implements this? Maybe do not touch `NewVersion()` for backward compatibility but introduce `NewVersionStrict()` or something like this.

Thanks!

**Comment by mitchellh** [comment]
This is intended. `go-version` supports SemVer but doesn't strictly enforce it. I admit we do a bad job of documenting where this is and we should try to improve that. There is another issue around here somewhere I think that recommends we introduce a _strict_ SemVer version type, which I'm completely in favor of. This type would enforce SemVer to the letter of the spec. 

This would free us up in the unstrict version to potentially support types of versions in the future (4 segments, whatever) as well. The utility of this is that we want go-version to be generally useful in parsing version numbers in the high percentile (95-99%) case.

**Comment by r0mant** [comment]
@mitchellh Thank you for clarification! I'm gonna close this for now then.
