### ISSUE TITLE
Support for zero padded numbers

### ISSUE THREAD

**Issue by febbraro** [hashicorp/go-version#27]
With the latest version scheme of Docker I found an interesting case where zero padded numbers are no longer zero padded when converted to a Version and then back to a string.  Example, `17.03.0-ce` becomes `17.3.0-ce`

Potentially related to #16 ?

**Comment by radeksimko** [comment]
This was implemented in https://github.com/hashicorp/go-version/pull/40 which also includes a test with that exact version.

Thank you for the report/suggestion.
