### ISSUE TITLE
compare with git tags: 1.2.0-2-g26fe0xx vs 1.2.0

### ISSUE THREAD

**Issue by choldrim** [hashicorp/go-version#29]
I generated version through `git describe --tags`, and found:
`1.2.0-2-g26fe0xx` should be bigger than `1.2.0`, but actually, go-version didn't.

**Comment by eversC** [comment]
the "_2-g26fe0xx_" string is considered to be the pre-release version (of 1.2.0), and "_1.2.0_" is the release version string

so in other words, the "_1.2.0_" version would be what you're happy people using in a prod environment, whereas "_1.2.0-2-g26fe0xx_" you wouldn't want people actually using in prod, therefore, the former is considered 'bigger' than the latter.

there's loads of online resources that describe how version strings are dissected in semver, but one that could be useful here (other than semver.org):
https://blog.gopheracademy.com/advent-2015/semver/

**Comment by mitchellh** [comment]
Yes I believe this is working as specified by semver. go-version allows non-semver compliant versions but given there is no single resource on how to order versions (many individuals believe their way is the right way), we decided to use semver as the guiding principle.
