### ISSUE TITLE
comparePart not comparing ints

### ISSUE THREAD

**Issue by eversC** [hashicorp/go-version#32]
`	v1, _ := version.NewVersion("v0.9.0-beta.4")`
`	v2, _ := version.NewVersion("v0.9.0-beta.15")`
`	fmt.Println(v1.Compare(v2))`

output: 1

I believe this happens because the comparePart() func is just doing string comparison on "4" and "15", of which 4 is deemed the larger. Whereas I think the comparison should be done on int64 when both 'self' and 'other' are ints, and comparison on strings when both are strings  (and the existing logic for when one but not the other is an int)

overall result should be that the output of my example is "-1"

semver (http://semver.org/#spec-item-11) says:

> identifiers consisting of only digits are compared numerically and identifiers with letters or hyphens are compared lexically in ASCII sort order.

**Comment by mitchellh** [comment]
Indeed, I agree your read of the spec is correct. This is a bug.
