### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by charlesvickery** [hashicorp/go-version#4]
I want to use [Sourcegraph](https://sourcegraph.com) for go-version code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/hashicorp/go-version. (It should only take 30 seconds.)

Thank you!

**Comment by mitchellh** [comment]
Sure, should be done.

**Comment by charlesvickery** [comment]
Great, thanks @mitchellh!

**Comment by mitchellh** [comment]
Ah, I see you work at Sourcegraph, and you probably don't actually have any interest at all in this repo on it. Deleting. I'm not a fan of these dishonest tactics.

I won't be using Sourcegraph again. Next time, just ask me that you'd like me to enable this so you can test your service.

**Comment by mitchellh** [comment]
My response was probably a bit harsh. I'm allergic to this kind of stuff. I apologize, but please, just be more up front about disclaiming you work for the company.

**Comment by charlesvickery** [comment]
Sorry @mitchellh, I should have been more clear in my intentions. Armon is speaking at our next meetup and I was planning to help promote this project to show off some of the work HashiCorp has been doing in addition to Consul. Didn't mean to spam at all.

**Comment by mitchellh** [comment]
@charlesvickery Thanks for the apology. I appreciate up front honesty quite a bit. I'll re-enable SG for this repo.

**Comment by mitchellh** [comment]
@charlesvickery Haha, now I can't because I revoked my GitHub auth access for SG and it looks like SG can't handle this yet? I'm getting a 401.

**Comment by charlesvickery** [comment]
Thanks @mitchellh, we'll look into it.

**Comment by charlesvickery** [comment]
Should be fixed now @mitchellh, thanks for the note and enabling this repository!
