### ISSUE TITLE
Malformed version for go1.11

### ISSUE THREAD

**Issue by 242617** [hashicorp/go-version#47]
OS: Ubuntu 18.10 x86_64,
Golang: go1.11.5
```
package main

import (
	"fmt"
	"runtime"

	version "github.com/hashicorp/go-version"
)

func main() {
	fmt.Println(runtime.Version())
	_, err := version.NewVersion(runtime.Version())
	if err != nil {
		panic(err)
	}
}
```

The `runtime.Version()` returns `go1.11`. And `err` is `Malformed version: go1.11`.

**Comment by mitchellh** [comment]
Thanks, but this is working as expected. The `NewVersion` expects a version string that is roughly semver compliant. In this case, if you supplied "1.11" it would work, but "go1.11" is not a valid version.
